require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

project 'TypescriptStarter',
  'Local.Debug' => :debug,
  'Local.Release' => :release,
  'Dev.Debug' => :debug,
  'Dev.Release' => :release,
  'Prod.Debug' => :debug,
  'Prod.Release' => :release

target 'TypescriptStarter' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'TypescriptStarterTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!(configurations: ['Local.Debug', 'Dev.Debug', 'Prod.Debug', 'Local.Release', 'Dev.Release', 'Prod.Release'])
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'TypescriptStarter-tvOS' do
  # Pods for TypescriptStarter-tvOS

  target 'TypescriptStarter-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
